// ============================================
// Internationalization (i18n) — Language System
// ============================================
// Supports: French (fr), Arabic (ar), English (en)
// Usage: const { t } = useLang();  →  t('dashboard')

import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    fr: {
        // ── Général ──
        dashboard: 'Tableau de bord',
        welcome: 'Bienvenue',
        welcomeBack: 'Bon retour',
        refresh: 'Actualiser',
        search: 'Rechercher expéditions, transporteurs, itinéraires...',
        loading: 'Chargement...',
        noData: 'Aucune donnée',
        close: 'Fermer',
        create: 'Créer',
        cancel: 'Annuler',
        save: 'Enregistrer',
        viewAll: 'Voir tout',
        all: 'Tous',
        delete: 'Supprimer',
        edit: 'Modifier',
        confirm: 'Confirmer',
        back: 'Retour',
        next: 'Suivant',
        submit: 'Soumettre',
        yes: 'Oui',
        no: 'Non',

        // ── Sidebar ──
        overview: 'Aperçu',
        analytics: 'Analytique',
        operations: 'Opérations',
        shipments: 'Expéditions',
        trips: 'Trajets',
        payments: 'Paiements',
        bids: 'Offres & Devis',
        management: 'Gestion',
        verification: 'Vérification',
        companyProfile: 'Profil de l\'entreprise',
        teamMembers: 'Membres de l\'équipe',
        settings: 'Paramètres',
        logout: 'Déconnexion',

        // ── Dashboard ──
        carrierWelcome: 'Gérez vos trajets et trouvez des expéditions correspondantes',
        shipperWelcome: 'Suivez vos expéditions et trouvez des transporteurs',
        myTrips: 'Mes trajets',
        myShipments: 'Mes expéditions',
        availableShipments: 'Expéditions disponibles',
        availableTrips: 'Trajets disponibles',
        activeRoutes: 'Routes actives',
        pendingMatches: 'Correspondances en attente',
        pending: 'En attente',
        inTransit: 'En transit',
        totalEarned: 'Total gagné',
        totalSpent: 'Total dépensé',
        commission: 'Commission',

        // ── Actions rapides ──
        quickActions: 'Actions rapides',
        publishTrip: 'Publier un trajet',
        publishShipment: 'Publier une expédition',
        findCarriers: 'Trouver des transporteurs',
        findShipments: 'Trouver des expéditions',
        payShipment: 'Payer une expédition',
        verifyCompany: 'Vérifier l\'entreprise',

        // ── Correspondance ──
        matchingShipments: 'Expéditions correspondantes',
        noMatchFound: 'Aucune correspondance trouvée pour ce trajet.',
        contactShipper: 'Contacter l\'expéditeur',
        placeBid: 'Faire une offre',
        manage: 'Gérer',

        // ── États vides ──
        noTripsYet: 'Pas encore de trajets',
        noTripsDesc: 'Publiez votre premier trajet pour commencer à trouver des correspondances.',
        noShipmentsYet: 'Pas encore d\'expéditions',
        noShipmentsDesc: 'Créez votre première expédition pour trouver des transporteurs.',
        noTripsAvailable: 'Aucun trajet disponible',
        noTripsAvailableDesc: 'Les trajets des transporteurs apparaîtront ici.',
        noShipmentsPosted: 'Pas d\'expéditions publiées',
        noShipmentsPostedDesc: 'Les expéditions des expéditeurs apparaîtront ici.',

        // ── Activité récente ──
        recentActivity: 'Activité récente',
        newShipmentCreated: 'Nouvelle expédition créée',
        paymentReceived: 'Paiement reçu',
        tripPublished: 'Trajet publié',

        // ── Statuts ──
        statusPending: 'En attente',
        statusPaid: 'Payé',
        statusCompleted: 'Terminé',
        statusInTransit: 'En transit',
        statusDelivered: 'Livré',
        statusActive: 'Actif',
        statusCancelled: 'Annulé',

        // ── Expéditions ──
        newShipment: 'Nouvelle expédition',
        shipmentTitle: 'Titre de l\'expédition',
        shipmentTitlePlaceholder: 'Pièces électroniques - Fragile',
        description: 'Description',
        descriptionPlaceholder: 'Détails sur le type de marchandise...',
        origin: 'Origine',
        originPlaceholder: 'Alger, Algérie',
        destination: 'Destination',
        destinationPlaceholder: 'Oran, Algérie',
        weightKg: 'Poids (kg)',
        dimensions: 'Dimensions',
        pickupDate: 'Date d\'enlèvement',
        deliveryDate: 'Date de livraison',
        budgetDZD: 'Budget (DZD)',
        searchShipments: 'Rechercher des expéditions...',
        shipperShipmentsDesc: 'Gérez et suivez vos expéditions de fret',
        carrierShipmentsDesc: 'Parcourez les expéditions disponibles et faites des offres',

        // ── Trajets ──
        newTrip: 'Nouveau trajet',
        departureDate: 'Date de départ',
        availableCapacity: 'Capacité disponible (kg)',
        pricePerKg: 'Prix par kg (DZD)',
        vehicleType: 'Type de véhicule',
        notes: 'Notes',
        searchTrips: 'Rechercher des trajets...',
        carrierTripsDesc: 'Gérez vos trajets et trouvez des correspondances',
        shipperTripsDesc: 'Parcourez les trajets disponibles',

        // ── Paiements ──
        amount: 'Montant',
        paymentMethod: 'Méthode de paiement',
        paymentStatus: 'Statut du paiement',
        totalPayments: 'Total des paiements',
        searchPayments: 'Rechercher des paiements...',

        // ── Connexion / Inscription ──
        login: 'Connexion',
        signup: 'Inscription',
        email: 'Adresse e-mail',
        password: 'Mot de passe',
        confirmPassword: 'Confirmer le mot de passe',
        companyName: 'Nom de l\'entreprise',
        iAmA: 'Je suis un',
        shipper: 'Expéditeur',
        carrier: 'Transporteur',
        createAccount: 'Créer un compte',
        alreadyHaveAccount: 'Vous avez déjà un compte ?',
        noAccount: 'Pas encore de compte ?',
        loginSubtitle: 'Connectez-vous à votre espace logistique',
        signupSubtitle: 'Commencez votre aventure logistique',
        signupFailed: 'Échec de l\'inscription',
        loginFailed: 'Échec de la connexion',

        // ── Vérification ──
        verificationTitle: 'Vérification de l\'entreprise',
        verificationDesc: 'Téléchargez vos documents pour vérifier votre entreprise',
        uploadDocument: 'Télécharger un document',
        documentType: 'Type de document',
        registreCommerce: 'Registre de commerce',
        nif: 'NIF',
        license: 'Licence',
        insurance: 'Assurance',
        idCard: 'Carte d\'identité',
        other: 'Autre',

        // ── Paramètres ──
        profileSettings: 'Paramètres du profil',
        settingsDesc: 'Gérez votre compte, sécurité et préférences',
        profileTab: 'Profil',
        securityTab: 'Sécurité',
        dangerZone: 'Zone de danger',
        personalInfo: 'Informations personnelles',
        personalInfoDesc: 'Modifiez votre nom et vos coordonnées',
        memberSince: 'Membre depuis',
        saveChanges: 'Enregistrer les modifications',
        profileUpdated: 'Profil mis à jour avec succès !',
        profileUpdateFailed: 'Échec de la mise à jour du profil',
        passwordDesc: 'Utilisez un mot de passe fort avec au moins 6 caractères',
        passwordsNoMatch: 'Les mots de passe ne correspondent pas',
        passwordTooShort: 'Le mot de passe doit contenir au moins 6 caractères',
        wrongPassword: 'Mot de passe incorrect',
        passwordChanged: 'Mot de passe changé avec succès !',
        passwordChangeFailed: 'Échec du changement de mot de passe',
        currentEmailLabel: 'E-mail actuel',
        emailChangeHint: 'Pour changer votre e-mail, allez dans l\'onglet Sécurité',
        fillAllFields: 'Veuillez remplir tous les champs',
        emailChanged: 'E-mail changé avec succès ! Reconnectez-vous.',
        emailChangeFailed: 'Échec du changement d\'e-mail',
        dangerDesc: 'Une fois votre compte désactivé, vous perdrez l\'accès à toutes les données.',
        enterPasswordConfirm: 'Entrez votre mot de passe pour confirmer',
        deactivateCheckbox: 'Je comprends que cette action désactivera mon compte',
        accountDeactivated: 'Compte désactivé. Déconnexion...',
        deactivateFailed: 'Échec de la désactivation',
        strong: 'Fort',
        medium: 'Moyen',
        weak: 'Faible',
        myTrips: 'Mes Trajets',
        availableTrips: 'Trajets Disponibles',
        carrierTripsDesc: 'Gérez vos itinéraires publiés',
        shipperTripsDesc: 'Parcourez les itinéraires des transporteurs',
        newTrip: 'Nouveau Trajet',
        availableCapacity: 'Capacité disponible (kg)',
        vehicleType: 'Type de véhicule',
        pricePerKg: 'Prix par kg (DZD)',
        matchingShipments: 'Expéditions correspondantes',
        noMatchFound: 'Aucune expédition correspondante trouvée',
        contactShipper: 'Contacter l\'expéditeur',
        searchTrips: 'Rechercher par ville...',
        noTripsYet: 'Aucun trajet publié pour le moment',
        noTripsDesc: 'Cliquez sur "Nouveau Trajet" pour publier votre premier itinéraire.',
        noTripsAvailable: 'Aucun trajet disponible',
        noTripsAvailableDesc: 'Revenez plus tard pour de nouveaux trajets.',
        route: 'Itinéraire',
        carrierPaymentsDesc: 'Suivez vos gains et paiements entrants',
        shipperPaymentsDesc: 'Gérez les paiements de vos expéditions',
        paymentCompletedMsg: 'Paiement terminé — livraison confirmée !',
        totalTransactions: 'Total des transactions',
        inProgress: 'En cours',
        noPaymentsYet: 'Aucun paiement pour le moment',
        noPaymentsCarrier: 'Les paiements apparaîtront ici quand les expéditeurs paieront.',
        noPaymentsShipper: 'Payez des expéditions pour voir votre historique.',
        shipmentPayment: 'Paiement d\'expédition',
        fee: 'Frais',
        confirmDelivery: 'Confirmer la livraison',
        originPlaceholder: 'ex: Alger, Algérie',
        destinationPlaceholder: 'ex: Oran, Algérie',
        departureDate: 'Date de départ',
        optional: 'Optionnel',
        all: 'Tout',
        pending: 'En attente',
        paid: 'Payé',
        completed: 'Terminé',
        refunded: 'Remboursé',
        cashOnDelivery: 'Paiement à la livraison',
        bankTransfer: 'Virement bancaire',
        companyInvoice: 'Facture entreprise',
        cashOnDeliveryDesc: 'Payez le chauffeur à la livraison',
        bankTransferDesc: 'Virement vers le compte du transporteur',
        companyInvoiceDesc: 'Recevez une facture, payez selon les termes',
        transactionRef: 'Référence de transaction',
        invoiceNumber: 'Numéro de facture / BC',
        bookingFailed: 'L\'inscription a échoué',
        weightTab: 'Poids',
        paymentTab: 'Paiement',
        confirmTab: 'Confirmer',
        shipmentWeight: 'Poids de l\'expédition',
        weightHint: 'Entrez le poids des marchandises que vous souhaitez expédier.',
        paymentMethod: 'Mode de paiement',
        paymentHint: 'Sélectionnez comment vous souhaitez payer.',
        confirmBooking: 'Confirmer la réservation',
        notesOptional: 'Notes (optionnel)',
        notesPlaceholder: 'Instructions spéciales, détails du fret...',
        bookingConfirmed: 'Réservation confirmée !',
        bookingConfirmedDesc: 'Votre expédition a été réservée avec succès.',
        bookingId: 'ID de réservation',
        done: 'Terminé',
        weightCap: 'Poids',
        total: 'Total',
        pickup: 'Enlèvement',
        view: 'Voir',
        findMatches: 'Trouver des correspondances',
        bookShipment: 'Réserver l\'expédition',
        firstName: 'Prénom',
        lastName: 'Nom',
        phone: 'Téléphone',
        changePassword: 'Changer le mot de passe',
        currentPassword: 'Mot de passe actuel',
        newPassword: 'Nouveau mot de passe',
        changeEmail: 'Changer l\'e-mail',
        newEmail: 'Nouvel e-mail',
        deactivateAccount: 'Désactiver le compte',

        // ── Langue ──
        language: 'Langue',
    },

    ar: {
        // ── عام ──
        dashboard: 'لوحة التحكم',
        welcome: 'مرحباً',
        welcomeBack: 'مرحباً بعودتك',
        refresh: 'تحديث',
        search: 'البحث عن شحنات، ناقلين، مسارات...',
        loading: 'جاري التحميل...',
        noData: 'لا توجد بيانات',
        close: 'إغلاق',
        create: 'إنشاء',
        cancel: 'إلغاء',
        save: 'حفظ',
        viewAll: 'عرض الكل',
        all: 'الكل',
        delete: 'حذف',
        edit: 'تعديل',
        confirm: 'تأكيد',
        back: 'رجوع',
        next: 'التالي',
        submit: 'إرسال',
        yes: 'نعم',
        no: 'لا',

        // ── الشريط الجانبي ──
        overview: 'نظرة عامة',
        analytics: 'التحليلات',
        operations: 'العمليات',
        shipments: 'الشحنات',
        trips: 'الرحلات',
        payments: 'المدفوعات',
        bids: 'العروض والأسعار',
        management: 'الإدارة',
        verification: 'التوثيق',
        companyProfile: 'ملف الشركة',
        teamMembers: 'أعضاء الفريق',
        settings: 'الإعدادات',
        logout: 'تسجيل الخروج',

        // ── لوحة التحكم ──
        carrierWelcome: 'أدر رحلاتك وابحث عن شحنات مطابقة',
        shipperWelcome: 'تابع شحناتك وابحث عن ناقلين',
        myTrips: 'رحلاتي',
        myShipments: 'شحناتي',
        availableShipments: 'الشحنات المتاحة',
        availableTrips: 'الرحلات المتاحة',
        activeRoutes: 'المسارات النشطة',
        pendingMatches: 'المطابقات المعلقة',
        pending: 'معلق',
        inTransit: 'قيد النقل',
        totalEarned: 'إجمالي الأرباح',
        totalSpent: 'إجمالي الإنفاق',
        commission: 'العمولة',

        // ── الإجراءات السريعة ──
        quickActions: 'إجراءات سريعة',
        publishTrip: 'نشر رحلة',
        publishShipment: 'نشر شحنة',
        findCarriers: 'البحث عن ناقلين',
        findShipments: 'البحث عن شحنات',
        payShipment: 'دفع شحنة',
        verifyCompany: 'توثيق الشركة',

        // ── المطابقة ──
        matchingShipments: 'الشحنات المطابقة',
        noMatchFound: 'لم يتم العثور على مطابقة لهذا المسار.',
        contactShipper: 'الاتصال بالشاحن',
        placeBid: 'تقديم عرض',
        manage: 'إدارة',

        // ── حالات فارغة ──
        noTripsYet: 'لا توجد رحلات بعد',
        noTripsDesc: 'انشر أول رحلة لبدء المطابقة مع الشحنات.',
        noShipmentsYet: 'لا توجد شحنات بعد',
        noShipmentsDesc: 'أنشئ أول شحنة للعثور على ناقلين.',
        noTripsAvailable: 'لا توجد رحلات متاحة',
        noTripsAvailableDesc: 'ستظهر رحلات الناقلين هنا.',
        noShipmentsPosted: 'لا توجد شحنات منشورة',
        noShipmentsPostedDesc: 'ستظهر شحنات الشاحنين هنا.',

        // ── النشاط الأخير ──
        recentActivity: 'النشاط الأخير',
        newShipmentCreated: 'شحنة جديدة تم إنشاؤها',
        paymentReceived: 'تم استلام الدفع',
        tripPublished: 'تم نشر رحلة',

        // ── الحالة ──
        statusPending: 'معلق',
        statusPaid: 'مدفوع',
        statusCompleted: 'مكتمل',
        statusInTransit: 'قيد النقل',
        statusDelivered: 'تم التوصيل',
        statusActive: 'نشط',
        statusCancelled: 'ملغي',

        // ── الشحنات ──
        newShipment: 'شحنة جديدة',
        shipmentTitle: 'عنوان الشحنة',
        shipmentTitlePlaceholder: 'قطع إلكترونية - هشة',
        description: 'الوصف',
        descriptionPlaceholder: 'تفاصيل عن نوع البضاعة...',
        origin: 'المصدر',
        originPlaceholder: 'الجزائر العاصمة',
        destination: 'الوجهة',
        destinationPlaceholder: 'وهران، الجزائر',
        weightKg: 'الوزن (كغ)',
        dimensions: 'الأبعاد',
        pickupDate: 'تاريخ الاستلام',
        deliveryDate: 'تاريخ التسليم',
        budgetDZD: 'الميزانية (د.ج)',
        searchShipments: 'البحث في الشحنات...',
        shipperShipmentsDesc: 'أدر وتابع شحنات البضائع الخاصة بك',
        carrierShipmentsDesc: 'تصفح الشحنات المتاحة وقدم عروضك',

        // ── الرحلات ──
        newTrip: 'رحلة جديدة',
        departureDate: 'تاريخ المغادرة',
        availableCapacity: 'السعة المتاحة (كغ)',
        pricePerKg: 'السعر لكل كغ (د.ج)',
        vehicleType: 'نوع المركبة',
        notes: 'ملاحظات',
        searchTrips: 'البحث في الرحلات...',
        carrierTripsDesc: 'أدر رحلاتك وابحث عن مطابقات',
        shipperTripsDesc: 'تصفح الرحلات المتاحة',

        // ── المدفوعات ──
        amount: 'المبلغ',
        paymentMethod: 'طريقة الدفع',
        paymentStatus: 'حالة الدفع',
        totalPayments: 'إجمالي المدفوعات',
        searchPayments: 'البحث في المدفوعات...',

        // ── تسجيل الدخول / إنشاء حساب ──
        login: 'تسجيل الدخول',
        signup: 'إنشاء حساب',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        confirmPassword: 'تأكيد كلمة المرور',
        companyName: 'اسم الشركة',
        iAmA: 'أنا',
        shipper: 'شاحن',
        carrier: 'ناقل',
        createAccount: 'إنشاء حساب',
        alreadyHaveAccount: 'لديك حساب بالفعل؟',
        noAccount: 'ليس لديك حساب؟',
        loginSubtitle: 'سجل دخولك إلى منصة اللوجستيك',
        signupSubtitle: 'ابدأ مغامرتك في عالم اللوجستيك',
        signupFailed: 'فشل إنشاء الحساب',
        loginFailed: 'فشل تسجيل الدخول',

        // ── التوثيق ──
        verificationTitle: 'توثيق الشركة',
        verificationDesc: 'ارفع مستنداتك للتحقق من شركتك',
        uploadDocument: 'رفع مستند',
        documentType: 'نوع المستند',
        registreCommerce: 'السجل التجاري',
        nif: 'الرقم الجبائي',
        license: 'الرخصة',
        insurance: 'التأمين',
        idCard: 'بطاقة الهوية',
        other: 'أخرى',

        // ── الإعدادات ──
        profileSettings: 'إعدادات الملف الشخصي',
        settingsDesc: 'أدر حسابك، الأمان والتفضيلات',
        profileTab: 'الملف الشخصي',
        securityTab: 'الأمان',
        dangerZone: 'منطقة الخطر',
        personalInfo: 'المعلومات الشخصية',
        personalInfoDesc: 'عدّل اسمك ومعلومات الاتصال',
        memberSince: 'عضو منذ',
        saveChanges: 'حفظ التغييرات',
        profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
        profileUpdateFailed: 'فشل تحديث الملف الشخصي',
        passwordDesc: 'استخدم كلمة مرور قوية لا تقل عن 6 أحرف',
        passwordsNoMatch: 'كلمتا المرور غير متطابقتين',
        passwordTooShort: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
        wrongPassword: 'كلمة المرور غير صحيحة',
        passwordChanged: 'تم تغيير كلمة المرور بنجاح!',
        passwordChangeFailed: 'فشل تغيير كلمة المرور',
        currentEmailLabel: 'البريد الحالي',
        emailChangeHint: 'لتغيير بريدك الإلكتروني، انتقل إلى تبويب الأمان',
        fillAllFields: 'يرجى ملء جميع الحقول',
        emailChanged: 'تم تغيير البريد الإلكتروني بنجاح! أعد تسجيل الدخول.',
        emailChangeFailed: 'فشل تغيير البريد الإلكتروني',
        dangerDesc: 'بمجرد تعطيل حسابك، ستفقد الوصول إلى جميع البيانات.',
        enterPasswordConfirm: 'أدخل كلمة المرور للتأكيد',
        deactivateCheckbox: 'أفهم أن هذا الإجراء سيعطّل حسابي',
        accountDeactivated: 'تم تعطيل الحساب. جاري تسجيل الخروج...',
        deactivateFailed: 'فشل تعطيل الحساب',
        strong: 'قوية',
        medium: 'متوسطة',
        weak: 'ضعيفة',
        myTrips: 'رحلاتي',
        availableTrips: 'الرحلات المتاحة',
        carrierTripsDesc: 'أدر مساراتك المنشورة',
        shipperTripsDesc: 'تصفح مسارات الناقلين',
        newTrip: 'رحلة جديدة',
        availableCapacity: 'السعة المتاحة (كغ)',
        vehicleType: 'نوع المركبة',
        pricePerKg: 'السعر للكيلوغرام (دج)',
        matchingShipments: 'شحنات متطابقة',
        noMatchFound: 'لم يتم العثور على شحنات متطابقة',
        contactShipper: 'اتصل بالمشحن',
        searchTrips: 'ابحث عن مدينة...',
        noTripsYet: 'لم تنشر أي رحلات بعد',
        noTripsDesc: 'انقر على "رحلة جديدة" لنشر أول مسار لك.',
        noTripsAvailable: 'لا توجد رحلات متاحة',
        noTripsAvailableDesc: 'تحقق لاحقاً من وجود رحلات جديدة.',
        route: 'المسار',
        carrierPaymentsDesc: 'تتبع أرباحك ومدفوعاتك الواردة',
        shipperPaymentsDesc: 'أدر مدفوعات شحناتك',
        paymentCompletedMsg: 'اكتمل الدفع — تم تأكيد التسليم!',
        totalTransactions: 'إجمالي المعاملات',
        inProgress: 'قيد التنفيذ',
        noPaymentsYet: 'لا توجد مدفوعات بعد',
        noPaymentsCarrier: 'ستظهر المدفوعات هنا عندما يدفع المشحنون.',
        noPaymentsShipper: 'ادفع ثمن الشحنات لرؤية سجل معاملاتك.',
        shipmentPayment: 'دفع شحنة',
        fee: 'رسوم',
        confirmDelivery: 'تأكيد التسليم',
        originPlaceholder: 'مثلاً: الجزائر العاصمة',
        destinationPlaceholder: 'مثلاً: وهران',
        departureDate: 'تاريخ المغادرة',
        optional: 'اختياري',
        all: 'الكل',
        pending: 'قيد الانتظار',
        paid: 'تم الدفع',
        completed: 'مكتمل',
        refunded: 'مسترجع',
        cashOnDelivery: 'الدفع عند التسليم',
        bankTransfer: 'تحويل بنكي',
        companyInvoice: 'فاتورة شركة',
        cashOnDeliveryDesc: 'ادفع للسائق عند التسليم',
        bankTransferDesc: 'تحويل إلى الحساب البنكي للناقل',
        companyInvoiceDesc: 'استلم فاتورة، وادفع حسب الشروط',
        transactionRef: 'مرجع المعاملة',
        invoiceNumber: 'رقم الفاتورة / أمر الشراء',
        bookingFailed: 'فشل الحجز',
        weightTab: 'الوزن',
        paymentTab: 'الدفع',
        confirmTab: 'تأكيد',
        shipmentWeight: 'وزن الشحنة',
        weightHint: 'أدخل وزن البضائع التي تريد شحنها.',
        paymentMethod: 'طريقة الدفع',
        paymentHint: 'اختر الطريقة التي تريد الدفع بها.',
        confirmBooking: 'تأكيد الحجز',
        notesOptional: 'ملاحظات (اختياري)',
        notesPlaceholder: 'تعليمات خاصة، تفاصيل الحمولة...',
        bookingConfirmed: 'تم تأكيد الحجز!',
        bookingConfirmedDesc: 'تم حجز شحنتك بنجاح.',
        bookingId: 'رقم الحجز',
        done: 'تم',
        weightCap: 'الوزن',
        total: 'الإجمالي',
        pickup: 'الاستلام',
        view: 'عرض',
        findMatches: 'البحث عن تطابقات',
        bookShipment: 'حجز الشحنة',
        firstName: 'الاسم الأول',
        lastName: 'اسم العائلة',
        phone: 'الهاتف',
        changePassword: 'تغيير كلمة المرور',
        currentPassword: 'كلمة المرور الحالية',
        newPassword: 'كلمة المرور الجديدة',
        changeEmail: 'تغيير البريد الإلكتروني',
        newEmail: 'البريد الإلكتروني الجديد',
        deactivateAccount: 'تعطيل الحساب',

        // ── اللغة ──
        language: 'اللغة',
    },

    en: {
        // ── General ──
        dashboard: 'Dashboard',
        welcome: 'Welcome',
        welcomeBack: 'Welcome back',
        refresh: 'Refresh',
        search: 'Search shipments, carriers, routes...',
        loading: 'Loading...',
        noData: 'No data',
        close: 'Close',
        create: 'Create',
        cancel: 'Cancel',
        save: 'Save',
        viewAll: 'View All',
        all: 'All',
        delete: 'Delete',
        edit: 'Edit',
        confirm: 'Confirm',
        back: 'Back',
        next: 'Next',
        submit: 'Submit',
        yes: 'Yes',
        no: 'No',

        // ── Sidebar ──
        overview: 'Overview',
        analytics: 'Analytics',
        operations: 'Operations',
        shipments: 'Shipments',
        trips: 'Trips',
        payments: 'Payments',
        bids: 'Bids & Quotes',
        management: 'Management',
        verification: 'Verification',
        companyProfile: 'Company Profile',
        teamMembers: 'Team Members',
        settings: 'Settings',
        logout: 'Logout',

        // ── Dashboard ──
        carrierWelcome: 'Manage your trips and find matching shipments',
        shipperWelcome: 'Track your shipments and find carriers',
        myTrips: 'My Trips',
        myShipments: 'My Shipments',
        availableShipments: 'Available Shipments',
        availableTrips: 'Available Trips',
        activeRoutes: 'Active Routes',
        pendingMatches: 'Pending Matches',
        pending: 'Pending',
        inTransit: 'In Transit',
        totalEarned: 'Total Earned',
        totalSpent: 'Total Spent',
        commission: 'Commission',

        // ── Quick Actions ──
        quickActions: 'Quick Actions',
        publishTrip: 'Publish Trip',
        publishShipment: 'Publish Shipment',
        findCarriers: 'Find Carriers',
        findShipments: 'Find Shipments',
        payShipment: 'Pay Shipment',
        verifyCompany: 'Verify Company',

        // ── Matching ──
        matchingShipments: 'Matching Shipments',
        noMatchFound: 'No matching shipments found for this route.',
        contactShipper: 'Contact Shipper',
        placeBid: 'Place Bid',
        manage: 'Manage',

        // ── Empty States ──
        noTripsYet: 'No trips yet',
        noTripsDesc: 'Publish your first trip to start getting matched with shipments.',
        noShipmentsYet: 'No shipments yet',
        noShipmentsDesc: 'Create your first shipment to find carriers.',
        noTripsAvailable: 'No trips available',
        noTripsAvailableDesc: 'Carrier trips will appear here.',
        noShipmentsPosted: 'No shipments posted',
        noShipmentsPostedDesc: 'Shipper shipments will appear here.',

        // ── Recent Activity ──
        recentActivity: 'Recent Activity',
        newShipmentCreated: 'New shipment created',
        paymentReceived: 'Payment received',
        tripPublished: 'Trip published',

        // ── Status ──
        statusPending: 'Pending',
        statusPaid: 'Paid',
        statusCompleted: 'Completed',
        statusInTransit: 'In Transit',
        statusDelivered: 'Delivered',
        statusActive: 'Active',
        statusCancelled: 'Cancelled',

        // ── Shipments ──
        newShipment: 'New Shipment',
        shipmentTitle: 'Shipment Title',
        shipmentTitlePlaceholder: 'Electronic Parts - Fragile',
        description: 'Description',
        descriptionPlaceholder: 'Details about the goods type...',
        origin: 'Origin',
        originPlaceholder: 'Algiers, Algeria',
        destination: 'Destination',
        destinationPlaceholder: 'Oran, Algeria',
        weightKg: 'Weight (kg)',
        dimensions: 'Dimensions',
        pickupDate: 'Pickup Date',
        deliveryDate: 'Delivery Date',
        budgetDZD: 'Budget (DZD)',
        searchShipments: 'Search shipments...',
        shipperShipmentsDesc: 'Manage and track your freight shipments',
        carrierShipmentsDesc: 'Browse available shipments and place bids',

        // ── Trips ──
        newTrip: 'New Trip',
        departureDate: 'Departure Date',
        availableCapacity: 'Available Capacity (kg)',
        pricePerKg: 'Price per kg (DZD)',
        vehicleType: 'Vehicle Type',
        notes: 'Notes',
        searchTrips: 'Search trips...',
        carrierTripsDesc: 'Manage your trips and find matches',
        shipperTripsDesc: 'Browse available trips',

        // ── Payments ──
        amount: 'Amount',
        paymentMethod: 'Payment Method',
        paymentStatus: 'Payment Status',
        totalPayments: 'Total Payments',
        searchPayments: 'Search payments...',

        // ── Login / Signup ──
        login: 'Login',
        signup: 'Sign Up',
        email: 'Email Address',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        companyName: 'Company Name',
        iAmA: 'I am a',
        shipper: 'Shipper',
        carrier: 'Carrier',
        createAccount: 'Create Account',
        alreadyHaveAccount: 'Already have an account?',
        noAccount: "Don't have an account?",
        loginSubtitle: 'Sign in to your logistics platform',
        signupSubtitle: 'Get started with freight logistics',
        signupFailed: 'Signup failed',
        loginFailed: 'Login failed',

        // ── Verification ──
        verificationTitle: 'Company Verification',
        verificationDesc: 'Upload your documents to verify your company',
        uploadDocument: 'Upload Document',
        documentType: 'Document Type',
        registreCommerce: 'Trade Register',
        nif: 'Tax ID (NIF)',
        license: 'License',
        insurance: 'Insurance',
        idCard: 'ID Card',
        other: 'Other',

        // ── Settings ──
        profileSettings: 'Profile Settings',
        settingsDesc: 'Manage your account, security, and preferences',
        profileTab: 'Profile',
        securityTab: 'Security',
        dangerZone: 'Danger Zone',
        personalInfo: 'Personal Information',
        personalInfoDesc: 'Update your name and contact details',
        memberSince: 'Member since',
        saveChanges: 'Save Changes',
        profileUpdated: 'Profile updated successfully!',
        profileUpdateFailed: 'Failed to update profile',
        passwordDesc: 'Use a strong password with at least 6 characters',
        passwordsNoMatch: 'Passwords do not match',
        passwordTooShort: 'Password must be at least 6 characters',
        wrongPassword: 'Wrong password',
        passwordChanged: 'Password changed successfully!',
        passwordChangeFailed: 'Failed to change password',
        currentEmailLabel: 'Current email',
        emailChangeHint: 'To change your email, go to the Security tab',
        fillAllFields: 'Please fill all fields',
        emailChanged: 'Email changed successfully! Please log in again.',
        emailChangeFailed: 'Failed to change email',
        dangerDesc: 'Once you deactivate your account, you will lose access to all data.',
        enterPasswordConfirm: 'Enter your password to confirm',
        deactivateCheckbox: 'I understand that this action will deactivate my account',
        accountDeactivated: 'Account deactivated. Logging out...',
        deactivateFailed: 'Failed to deactivate',
        strong: 'Strong',
        medium: 'Medium',
        weak: 'Weak',
        myTrips: 'My Trips',
        availableTrips: 'Available Trips',
        carrierTripsDesc: 'Manage your published routes',
        shipperTripsDesc: 'Browse carrier routes',
        newTrip: 'New Trip',
        availableCapacity: 'Available Capacity (kg)',
        vehicleType: 'Vehicle Type',
        pricePerKg: 'Price per kg (DZD)',
        matchingShipments: 'Matching Shipments',
        noMatchFound: 'No matching shipments found',
        contactShipper: 'Contact Shipper',
        searchTrips: 'Search by city...',
        noTripsYet: 'No trips published yet',
        noTripsDesc: 'Click "New Trip" to publish your first route.',
        noTripsAvailable: 'No trips available',
        noTripsAvailableDesc: 'Check back later for new carrier routes.',
        route: 'Route',
        carrierPaymentsDesc: 'Track your earnings and payments',
        shipperPaymentsDesc: 'Manage your shipment payments',
        paymentCompletedMsg: 'Payment completed — delivery confirmed!',
        totalTransactions: 'Total Transactions',
        inProgress: 'In Progress',
        noPaymentsYet: 'No payments yet',
        noPaymentsCarrier: 'Payments will appear here once shippers pay.',
        noPaymentsShipper: 'Pay for shipments to see history.',
        shipmentPayment: 'Shipment Payment',
        fee: 'Fee',
        confirmDelivery: 'Confirm Delivery',
        originPlaceholder: 'e.g. Alger, Algeria',
        destinationPlaceholder: 'e.g. Oran, Algeria',
        departureDate: 'Departure Date',
        optional: 'Optional',
        all: 'All',
        pending: 'Pending',
        paid: 'Paid',
        completed: 'Completed',
        refunded: 'Refunded',
        cashOnDelivery: 'Cash on Delivery',
        bankTransfer: 'Bank Transfer',
        companyInvoice: 'Company Invoice',
        cashOnDeliveryDesc: 'Pay the driver upon delivery',
        bankTransferDesc: 'Transfer to carrier bank account',
        companyInvoiceDesc: 'Receive an invoice, pay within terms',
        transactionRef: 'Transaction Reference',
        invoiceNumber: 'Invoice / PO Number',
        bookingFailed: 'Booking failed',
        weightTab: 'Weight',
        paymentTab: 'Payment',
        confirmTab: 'Confirm',
        shipmentWeight: 'Shipment Weight',
        weightHint: 'Enter the weight of goods you want to ship.',
        paymentMethod: 'Payment Method',
        paymentHint: 'Select how you would like to pay.',
        confirmBooking: 'Confirm Booking',
        notesOptional: 'Notes (optional)',
        notesPlaceholder: 'Special instructions, cargo details...',
        bookingConfirmed: 'Booking Confirmed!',
        bookingConfirmedDesc: 'Your shipment has been booked successfully.',
        bookingId: 'Booking ID',
        done: 'Done',
        weightCap: 'Weight',
        total: 'Total',
        pickup: 'Pickup',
        view: 'View',
        findMatches: 'Find Matches',
        bookShipment: 'Book Shipment',
        firstName: 'First Name',
        lastName: 'Last Name',
        phone: 'Phone',
        changePassword: 'Change Password',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        changeEmail: 'Change Email',
        newEmail: 'New Email',
        deactivateAccount: 'Deactivate Account',

        // ── Language ──
        language: 'Language',
    },
};

const LangContext = createContext();

export function LangProvider({ children }) {
    const [lang, setLang] = useState(() => localStorage.getItem('routeur_lang') || 'fr');

    useEffect(() => {
        localStorage.setItem('routeur_lang', lang);
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = lang;
    }, [lang]);

    const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

    return (
        <LangContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LangContext.Provider>
    );
}

export function useLang() {
    const context = useContext(LangContext);
    if (!context) throw new Error('useLang must be used within LangProvider');
    return context;
}

export const LANGUAGES = [
    { code: 'fr', label: 'Français', flag: '🇫🇷' },
    { code: 'ar', label: 'العربية', flag: '🇩🇿' },
    { code: 'en', label: 'English', flag: '🇬🇧' },
];

export default translations;
